apiVersion: argoproj.io/v1alpha1
kind: Rollout  # Different kind!
metadata:
  name: vote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: schoolofdevops/vote:v2
        ports:
        - containerPort: 80
  strategy:
    blueGreen:  # Advanced strategy!
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      activeService: vote
      previewService: vote-preview